### ISSUE TITLE
Missing arm image for 0.3.0

### ISSUE THREAD

**Issue by Azokul** [seriohub/vui-api#62]
Hi, 
Would you be able to update to make a 0.3.0 arm image?
I tried to do mine, but it doesn't seem to like something related to FASTAPI version once deployed.
Thanks in advance :)

**Comment by davideserio** [comment]
Hi,
I've deployed a new image with the dev tag, you can try using that.
In your values.yaml or override.yaml, set:


```yaml
apiService:
  deployment:
    image:
      tag: dev
    imagePullPolicy: Always
```

Let me know how it goes!
